<center> <h1>Universidad Nacional de San Agustín de Arequipa</h1> </center> 
<center> <h1>Escuela Profesional de Ingeniería de Telecomunicaciones</h1> </center> 

<center> <h1> </h1> </center> 

<center><img src="https://user-images.githubusercontent.com/19308295/115939517-f1c6fe80-a463-11eb-989c-812ab4942586.png" width="380" height="4200"></center>

<center> <h2>Ingeniero Renzo Bolivar - Docente DAIE</h2> </center> 

<center> <h1>Curso : Computación 2</h1> </center> 

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

## <font color=#33A5FF>****EJERCICIOS****<tfont>

<center> <h2>Ejercicio 03</h2> </center> 

* Crea una matriz aleatoria 7x7 y halla los valores mínimo y máximo.
* Normaliza la matriz anterior entre 0 y 1.

In [29]:
#primera forma
jk =np.random.randint(1,69,(7,7))

print(jk)

print("El valor maximo es",jk.min())

print("El valor minimo es",jk.max())

print("La sumatoria es",jk.sum())


print("RECUERDEN ESTO VARIA POR QUE ES ALEATORIO")

[[23 39 52 12 59 37  9]
 [18 68 33 28 24 20  4]
 [18 41 11 28 18 64 25]
 [58 15 64 42 50 54 29]
 [59 40  9 12 46 24 31]
 [30 50 25 63 60 19  4]
 [29 66 17 41 32 18 17]]
El valor maximo es 4
El valor minimo es 68
La sumatoria es 1635
RECUERDEN ESTO VARIA POR QUE ES ALEATORIO


In [30]:
#segunda forma
al =np.random.random((7,7))

print(al)

print("El valor maximo es",al.min())

print("El valor minimo es",al.max())

print("La sumatoria es",al.sum())


print("RECUERDEN ESTO VARIA POR QUE ES ALEATORIO")


[[0.66889445 0.20609812 0.3260299  0.18111685 0.12735078 0.77164101
  0.66301846]
 [0.29204685 0.08189635 0.25647247 0.41483518 0.72470429 0.06943087
  0.48582028]
 [0.38643093 0.03848486 0.00616512 0.8607093  0.85575278 0.83339463
  0.67064781]
 [0.71118585 0.08636015 0.8803446  0.0749743  0.31024772 0.66691879
  0.68562422]
 [0.44692502 0.96298914 0.5368981  0.1680106  0.35116027 0.42489463
  0.65866481]
 [0.99850978 0.08963412 0.32604063 0.33829401 0.34570106 0.38531853
  0.84046454]
 [0.92234657 0.21745742 0.87405791 0.11154821 0.87268998 0.96644718
  0.15042682]]
El valor maximo es 0.006165115497474782
El valor minimo es 0.9985097817406966
La sumatoria es 23.32507624983618
RECUERDEN ESTO VARIA POR QUE ES ALEATORIO


![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)