  
### Autor : Arenas Lopez Larry Stewart
## NUMPY 


#### Matriz unidimensional
Con la primera instrucción import numpy as np le estamos indicando a nuestro
programa de Python que de ahora en adelante np será la referencia para todo lo
referente a NumPy.

In [3]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


#### Matriz bidimensional

In [4]:
b=np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
array=np.array([[1,2,3,4],[5,6,7,8]],dtype=np.int64)
print(array)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
import sys
S=range(1000)
print(sys.getsizeof(5)*len(S))

28000


In [7]:
D=np.arange(1000)
print(D.size*D.itemsize)

8000


In [1]:
import time

SIZE = 1000000

L1=range(SIZE)
L2=range(SIZE)

start= time.time()
result=[(x,y) for x,y in zip(L1,L2)] 
print((time.time()-start)*1000) 

157.03225135803223


In [4]:
A1=np.arange(SIZE)
A2=np.arange(SIZE)

start=time.time()
result=A1+A2                   
print((time.time()-start)*1000)

93.66822242736816


In [5]:
unos= np.ones((3,4))
print (unos)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### Crea una matriz de ceros - 3 filas 4 columanas


In [6]:
ceros= np.zeros((3,4))
print (ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Crea una matriz con valores aleatorios


In [7]:
aleatorios=np.random.random((2,2))
print(aleatorios)

[[0.27575199 0.47879095]
 [0.76520082 0.13040837]]


#### Crear una matriz vacía


In [9]:
vacia = np.empty((3,2))
print (vacia)

[[4.66447376e-320 0.00000000e+000]
 [4.21572691e-297 6.72940615e-239]
 [1.27339630e-312 2.39010012e-253]]


#### Crea una matriz con un solo valor


In [10]:
full = np.full((2,2),8)
print(full)

[[8 8]
 [8 8]]


#### Crea una matriz con valores esparcidos uniformemente 

In [12]:
espacio1 = np.arange(0,30,5)
print(espacio1)

[ 0  5 10 15 20 25]


In [13]:
espacio2 = np.linspace(0,2,5)
print(espacio2)

[0.  0.5 1.  1.5 2. ]


#### Crear una matriz identidad

In [14]:
identidad1 = np.eye(4,4)
print(identidad1)

identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### Conocer las dimensiones de una matriz


In [16]:
a = np.array([(1,2,3),(4,5,6)])

print (a.ndim)

2


#### Conocer el tipo de los datos

In [17]:
print (a.dtype)

int64


#### Conocer el tamaño y forma de la matriz


In [19]:
a = np.array([(1,2,3,4,5,6)])

print (a.size)
print (a.shape)

6
(1, 6)


#### Cambio de forma de una matriz


In [20]:
a = np.array([(8,9,10),(11,12,13)]) #2 filas x 3 culumnas
print (a)
a=a.reshape(3,2) # 3 filas x 2 columnas 
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


#### Extraer un solo valor de la matriz - el valor ubicado en la fila 0 columna 2


In [21]:
a = np.array([(1,2,3,4),(3,4,5,6)])
print (a[0,2])

3


#### Extraer los valores de todas las filas ubicados en la columna 3 


In [22]:
a = np.array([(1,2,3,4),(3,4,5,6)])
print (a[0:,2])

[3 5]


#### Encontrar el mínimo, máximo y la suma


In [23]:
a = np.array([(2,45,800)])
print(a.min())
print(a.max())
print(a.sum())

2
800
847


#### Calcular la raíz cuadrada y la desviación estándar


In [24]:
a = np.array([(1,4,81),(33,44,50)])
print(np.sqrt(a))
print(np.std(a))

[[1.         2.         9.        ]
 [5.74456265 6.63324958 7.07106781]]
27.5121185419565


#### Calcular la suma, resta, multiplicación y división de dos matrices


In [ ]:
x = np.array([(1,2,3),(3,4,5,)])
y = np.array([(1,2,3),(3,4,5)])
print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)

### EJERCICIOS

#### Cree una matriz de 5*5 con los valores  1,2,3,4 justo debajo de la diagonal


In [25]:
import numpy as np
a = np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### Crea un vector aleatorio de tamaño 30 y encuentra el valor medio


In [26]:
b = np.random.random(30)
m = b.mean()
print(m)

0.5371220900694115


#### ¿Como ordenar una matriz por enecima colunma?


In [27]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[9 2 9]
 [9 8 5]
 [3 1 2]]
[[3 1 2]
 [9 2 9]
 [9 8 5]]


#### Como agregar un borde ( lleno de 0) alrededor de una matriz existente


In [28]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
