In [1]:
import numpy np
array1 = np.zeros ((7,8), dtype=int)print (array1)

SyntaxError: invalid syntax (1850105665.py, line 1)

In [2]:
import numpy as np
array 1 = np.zeros ((7,8), dtype=int)
print ("Array 7*8 lleno de ceros de tipo entero :")
print (array1)

SyntaxError: invalid syntax (3528770401.py, line 2)

In [3]:
import numpy as np

# 1. Array 7x8 lleno de ceros de tipo entero
array1 = np.zeros((7, 8), dtype=int)
print("Array 7x8 lleno de ceros de tipo entero:")
print(array1)

# 2. Array 7x8 lleno de ceros salvo la primera fila que serán todo unos
array2 = np.zeros((7, 8), dtype=int)
array2[0, :] = 1
print("\nArray 7x8 lleno de ceros salvo la primera fila que serán todo unos:")
print(array2)

# 3. Array 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 12
array3 = np.zeros((7, 8), dtype=int)
array3[-1, :] = np.arange(5, 13)
print("\nArray 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 12:")
print(array3)


Array 7x8 lleno de ceros de tipo entero:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

Array 7x8 lleno de ceros salvo la primera fila que serán todo unos:
[[1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

Array 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 12:
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 5  6  7  8  9 10 11 12]]
