In [1]:
import numpy as np 
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# matriz bidimensional 
b=np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
array=np.array ([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
print (array)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
# POR QUE USAR NUMPY
# Cantidad de memoria asignada 
import sys 
S=range(1000)
print(sys.getsizeof(5)*len(S))

28000


In [ ]:
D=np