In [ ]:
# EJERCCIO 4
# de la siguente matriz

<img src="https://user-images.githubusercontent.com/19308295/115969506-dbbc4b00-a502-11eb-9c76-c9da265c5366.png"
    style="width:400px"></img>

In [1]:
# luego invertir lo valores de 9 y 1 de la matriz anterior
import numpy as np

matriz2=np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]])

 
for i in range(0, 5):
    for j in range(0, 5):
        valor = matriz2[i][j]
        if valor == 9:
            matriz2[i][j] = 1
        if valor == 1:
            matriz2[i][j] = 9
 
print(matriz2)

[[9 9 9 9 9]
 [9 0 0 0 9]
 [9 0 1 0 9]
 [9 0 0 0 9]
 [9 9 9 9 9]]
