In [ ]:
# UNIVERSIDAD  NACIONAL DE SAN AGUSTIN DE AREQUIPA 
# ALUMNO: Capatinta Garate Yeferson Jose 

In [3]:
# MATRIZ UNIDIMECIONAL
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# MATRIZ BIDIMENCIONAL
b=np.array([(1,2,3),(4,5,6)])
print (b)

[[1 2 3]
 [4 5 6]]


In [4]:
array=np.array([(1,2,3,4),(5,6,7,8)], dtype=np.int64)
print(array)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# PORQUE USAR NUMPY

In [5]:
# cantidad de memoria asignada
import sys
s=range(1000)
print (sys.getsizeof(5)*len(s))

28000


In [6]:
D=np.arange(1000)
print(D.size*D.itemsize)

4000


In [7]:
# velocidad
import time

SIZE = 1000000

L1=range(SIZE)
L2=range(SIZE)

start= time.time()
result=[(x,y) for x,y in zip(L1,L2)] 
print((time.time()-start)*1000) 

537.161111831665


In [8]:
A1=np.arange(SIZE)
A2=np.arange(SIZE)

start=time.time()
result=A1+A2                    #solo se suma
print((time.time()-start)*1000) #velocidad de numpy

186.35964393615723


In [ ]:
# MATRICES VACIAS 

In [9]:
#crea una matriz de unos - 3 filas 4 columanas
unos= np.ones((3,4))
print (unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
#crea una matriz de ceros - 3 filas 4 columanas
ceros= np.zeros((3,4))
print (ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
#Crea una matriz con valores aleatorios
aleatorios=np.random.random((2,2))
print(aleatorios)

[[0.40863643 0.97563818]
 [0.93387532 0.81262847]]


In [12]:
#Crear una matriz vacía
vacia = np.empty((3,2))
print (vacia)

[[-9.17579026e-312 -1.09138288e+044]
 [ 9.17567112e-312  9.17567112e-312]
 [ 1.03753786e-322  1.72922976e-322]]


In [14]:
#Crea una matriz con un solo valor
full = np.full((2,2),8)
print(full)

[[8 8]
 [8 8]]


In [16]:
#Crea una matriz con valores esparcidos uniformemente 
espacio1 = np.arange(0,30,5)
print(espacio1)

[ 0  5 10 15 20 25]


In [17]:
espacio2 = np.linspace(0,2,5)
print(espacio2)

[0.  0.5 1.  1.5 2. ]


In [18]:
#Crear una matriz identidad
identidad1 = np.eye(4,4)
print(identidad1)

identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# INSPECCIONAR LAS MATRICES DE NUMPY

In [19]:
# Conocer las dimensiones de una matriz
a = np.array([(1,2,3),(4,5,6)])

print (a.ndim)

2


In [20]:
# Conocer el tipo de los datos
print (a.dtype)

int32


In [21]:
# Conocer el tamaño y forma de la matriz
a = np.array([(1,2,3,4,5,6)])

print (a.size)
print (a.shape)

6
(1, 6)


In [23]:
# Cambio de forma de una matriz
a = np.array([(8,9,10),(11,12,13)]) #2 filas x 3 culumnas
print (a)
a=a.reshape(3,2) # 3 filas x 2 columnas 
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [24]:
# Extraer un solo valor de la matriz - el valor ubicado en la fila 0 columna 2
a = np.array([(1,2,3,4),(3,4,5,6)])
print (a[0,2])

3


In [25]:
# Extraer los valores de todas las filas ubicados en la columna 3 
a = np.array([(1,2,3,4),(3,4,5,6)])
print (a[0:,2])

[3 5]


In [26]:
# OPERACIONES MATEMATICAS ENTRE MATRICES DE NUMPY

In [27]:
# Encontrar el mínimo, máximo y la suma
a = np.array([(2,45,800)])
print(a.min())
print(a.max())
print(a.sum())

2
800
847


In [28]:
# Calcular la raíz cuadrada y la desviación estándar
a = np.array([(1,4,81),(33,44,50)])
print(np.sqrt(a))
print(np.std(a))

[[1.         2.         9.        ]
 [5.74456265 6.63324958 7.07106781]]
27.5121185419565


In [29]:
# Calcular la suma, resta, multiplicación y división de dos matrices
x = np.array([(1,2,3),(3,4,5,)])
y = np.array([(1,2,3),(3,4,5)])
print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)

[[ 2  4  6]
 [ 6  8 10]]

[[0 0 0]
 [0 0 0]]

[[ 1  4  9]
 [ 9 16 25]]

[[1. 1. 1.]
 [1. 1. 1.]]


In [30]:
# EJEMPLOS 

In [31]:
# 1.cree una matriz de 5*5 con los valores  1,2,3,4 justodebajo de la diagonal
import numpy as np
a = np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [32]:
# 2. crea un vector aleatorio de tamaño 30 y encuentra el valor medio
b = np.random.random(30)
m = b.mean()
print(m)

0.5653549516408591


In [33]:
# 3. ¿como ordenar una matriz por enecima colunma?
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[6 6 4]
 [3 6 7]
 [9 9 1]]
[[6 6 4]
 [3 6 7]
 [9 9 1]]


In [34]:
# 4. como agregar un borde ( lleno de 0) alrededor de una matriz existente
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
