In [5]:
# EJERCICIO 2
# crea un vector de 10 elementos, siendo los impares 1 y los pares 2
import numpy as np
a=np.array([1,2])
print(a)

[1 2]


In [6]:
a_nuevo= np.tile(a,5)
print (a_nuevo)

[1 2 1 2 1 2 1 2 1 2]


In [7]:
# crea un "tablero de ajedrez" 8*8 con 1 en las casillas negras y 0 en las casillas blancas
import numpy as np
ajedrez = np.zeros((8,8),dtype=int)
print(ajedrez)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [8]:
ajedrez[::2, 1::2]=1
print(ajedrez)

[[0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]]


In [9]:
ajedrez[1::2, ::2] = 1
print(ajedrez)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
