In [13]:
import numpy as np
#Crear un array 7x8 lleno de ceros de tipo entero.

array1 = np.zeros ((7,8), dtype=int)
print (array1)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [14]:
#Crear un array 7x8 lleno de ceros salvo la primera fila que serán todo unos.

array2 = np.zeros ((7,8), dtype=int)
print("Array 7*8 lleno de ceros que serán unos :")
for i in range(8):
    array2[0][i]=1  
print(array2)

Array 7*8 lleno de ceros que serán unos :
[[1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [15]:
# Crear un array 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 8.

array3 = np.zeros((7, 8), dtype=int)
for i in range(8):
    array3[6][i]=5
print(array3)


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [5 5 5 5 5 5 5 5]]
