<center> <h1>Universidad Nacional de San Agustín de Arequipa</h1> </center> 
<center> <h1>Escuela Profesional de Ingeniería de Telecomunicaciones</h1> </center> 

<center> <h1> </h1> </center> 

<center><img src="https://user-images.githubusercontent.com/19308295/115939517-f1c6fe80-a463-11eb-989c-812ab4942586.png" width="380" height="4200"></center>
<center> <h2>Ingeniero Renzo Bolivar - Docente DAIE</h2> </center> 
<center> <h1>Curso : Computación 2</h1> </center> 

## <font color=#33A5FF>****EJERCICIOS****<tfont>

In [2]:
import numpy as np
#Crear un array 7x8 lleno de ceros de tipo entero.

array1 = np.zeros ((7,8), dtype=int)
print (array1)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [3]:
#Crear un array 7x8 lleno de ceros salvo la primera fila que serán todo unos.

array2 = np.zeros ((7,8), dtype=int)
print("Array 7*8 lleno de ceros que serán unos :")
for i in range(8):
    array2[0][i]=1  
print(array2)

Array 7*8 lleno de ceros que serán unos :
[[1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [11]:
# Crear un array 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 8.

array3 = np.zeros((7, 8), dtype=int)
for i in range(8):
    random_integer = np.random.randint(5, 9)
    array3[6][i]=random_integer
print(array3)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [5 6 6 5 7 7 8 7]]
